### ISSUE TITLE
0.3版代理无效

### ISSUE THREAD

**Issue by shengxihu** [Muxi-Studio/ninja#13]
0.3版本的代理无效，ninja.conf.js的proxy接口在与0.2版本相同配置的情况下，0.3版本发送ajax的路径是：localhost:3000+url,如下图：
<img style="height:50px;" src='http://oev2d4dz7.bkt.clouddn.com/5B06583464473F89D07775339EA2BAFB.png'/>

**Comment by zxc0328** [comment]
fixed in https://github.com/Muxi-Studio/ninja/commit/ff47fbb0667baca242ca0a6a0eec8fb730c48c48
